"""Build the README results block from files written by the pipeline. No number is typed by hand.

Run:  python -m scripts.build_summary
Rewrites the text between the RESULTS markers in README.md.
"""
from __future__ import annotations

import json
import re

import pandas as pd

from src.bball.config import ROOT, load_config, resolve

START = "<!-- RESULTS:START (generated by scripts/build_summary.py; do not edit) -->"
END = "<!-- RESULTS:END -->"


def md_table(df: pd.DataFrame) -> str:
    cols = [str(c) for c in df.columns]
    lines = ["| " + " | ".join(cols) + " |", "|" + "|".join("---" for _ in cols) + "|"]
    for row in df.itertuples(index=False):
        lines.append("| " + " | ".join("" if pd.isna(v) else str(v) for v in row) + " |")
    return "\n".join(lines)


def build() -> str:
    cfg = load_config()
    res = resolve(cfg["paths"]["results"])
    v = res / "video"
    if not (v / "summary.json").exists():
        return "\n\n".join([START, "_Run the video pipeline to generate results (see above)._", END])
    s = json.loads((v / "summary.json").read_text())
    q = s["quality"]
    names = cfg["video"]["teams"]
    parts = ["### Video analysis results (clip: " + f"{s['clip_seconds']:.0f} s of broadcast footage)\n"]
    parts.append(md_table(pd.DataFrame([
        ["Camera shots longer than 1 s that show the court (analysed)", f"{s['usable_shots']} shots, {s['analysed_seconds']:.0f} s "
         f"({s['analysed_seconds'] / s['clip_seconds']:.0%} of the clip)"],
        ["Frames mapped to court metres", f"{q['mapped_frames']} of {q['analysed_frames']} analysed frames "
         f"({q['mapped_frames'] / q['analysed_frames']:.0%})"],
        ["Median feature matches / painted-line alignment score of mapped frames",
         f"{q['feature_matches_median']} / {q['alignment_score_median']}"],
        ["Players labelled per mapped frame (median)", q["players_labelled_per_mapped_frame_median"]],
        ["Mapped frames with 8+ players labelled", f"{q['mapped_frames_with_8_or_more_players_labelled']:.0%}"],
        ["Ball position known (detected or briefly interpolated)", f"{s['ball_share_of_mapped_frames']:.0%} of mapped frames"],
        ["Ball detector", s["ball_source"]],
    ], columns=["Quantity", "Value"])))
    ts = pd.DataFrame(s["team_stats"]).T.reset_index().rename(columns={"index": "team"})
    ts = ts[["team", "kit", "passes", "interceptions", "possession_pct", "distance_m_tracked_players"]]
    parts.append("\n#### Team statistics from the video (estimates, this clip only)\n")
    parts.append(md_table(ts))
    ctx = s.get("official_period_context")
    if ctx:
        parts.append(f"\nOfficial NBA.com context for the same quarter (period {ctx['period']}): "
                     f"steals {ctx['steals_by_team']}, turnovers {ctx['turnovers_by_team']}. The clip shows "
                     f"{s['analysed_seconds']:.0f} s of court-view footage, and the video 'interceptions' also "
                     "include deflections and loose-ball changes that the scorer does not log as steals, so "
                     "these numbers are not expected to match.")
    if (v / "players.csv").exists():
        pl = pd.read_csv(v / "players.csv")
        top = pl.sort_values("distance_m", ascending=False).head(8)[
            ["pid", "team_name", "seconds_tracked", "distance_m", "avg_speed_kmh", "top_speed_kmh"]]
        parts.append(f"\n#### Per-player distance and speed: {len(pl)} tracked player chains; the 8 with most distance\n")
        parts.append(md_table(top))
    vc = res / "ball_model" / "visual_check.json"
    if vc.exists():
        c = json.loads(vc.read_text())
        parts.append(f"\n#### Ball detector, checked by eye on random frames (not ground truth)\n\n"
                     f"{c['summary']}")
    return "\n\n".join([START] + parts + [END])


def splice(block: str) -> None:
    readme = ROOT / "README.md"
    text = readme.read_text(encoding="utf-8")
    pat = re.compile(re.escape(START.split(" (")[0]) + r".*?" + re.escape(END), re.S)
    if not pat.search(text):
        raise SystemExit("README.md has no RESULTS markers")
    readme.write_text(pat.sub(lambda _: block, text), encoding="utf-8")
    (resolve(load_config()["paths"]["results"]) / "README_results_block.md").write_text(block, encoding="utf-8")


if __name__ == "__main__":
    splice(build())
    print("README results block updated")
